# Generated by Django 6.0.2 on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_comment_like"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "deleted", "-created"],
                name="post_author_del_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["visibility", "deleted", "-created"],
                name="post_vis_del_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "-published"],
                name="comment_post_pub_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["post", "-created"],
                name="like_post_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="like",
            index=models.Index(
                fields=["comment", "-created"],
                name="like_comment_created_idx",
            ),
        ),
    ]