# Generated by Django 6.0.2 on 2026-03-19 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_is_remote_comment_remote_id_like_is_remote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_author_post_like',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_author_comment_like',
        ),
        migrations.AddField(
            model_name='comment',
            name='remote_author_host',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='remote_author_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='remote_author_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='remote_author_host',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='remote_author_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='remote_author_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='remote_author_host',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='remote_author_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='remote_author_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='remote_id',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='remote_id',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='remote_id',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_remote', 'remote_id'], name='comment_remote_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['is_remote', 'remote_id'], name='like_remote_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_remote', 'remote_id'], name='post_remote_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('author__isnull', False), ('post__isnull', False)), fields=('author', 'post'), name='unique_author_post_like'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(condition=models.Q(('author__isnull', False), ('comment__isnull', False)), fields=('author', 'comment'), name='unique_author_comment_like'),
        ),
    ]
