# Generated by Django 6.0.2 on 2026-03-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_like_unique_author_post_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='remote_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
