# Generated by Django 6.0.2 on 2026-03-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_remote_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('text/plain', 'Plain text'), ('text/markdown', 'Markdown'), ('image/png;base64', 'Image (PNG, base64)'), ('image/jpeg;base64', 'Image (JPEG, base64)')], default='text/markdown', max_length=50),
        ),
    ]
