# Generated by Django 6.0.2 on 2026-03-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='remote_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
