# Generated by Django 6.0.2 on 2026-03-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='remote_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
