# Generated by Django 6.0.2 on 2026-03-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
