# Generated by Django 6.0.2 on 2026-03-04 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_author_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='approved',
            new_name='is_approved',
        ),
    ]
