# Generated by Django 6.0.2 on 2026-03-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_rename_approved_author_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
