# Generated by Django 6.0.2 on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0005_rename_approved_author_is_approved"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="follower",
            index=models.Index(fields=["follower", "status"], name="follower_status_idx"),
        ),
        migrations.AddIndex(
            model_name="follower",
            index=models.Index(fields=["following", "status"], name="following_status_idx"),
        ),
    ]