# Generated by Django 6.0.2 on 2026-03-15 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_add_follower_indexes'),
        ('authors', '0006_alter_author_profileimage'),
    ]

    operations = [
    ]
