# Generated by Django 6.0.2 on 2026-03-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_merge_20260315_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='remote_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
