# Generated by Django 6.0.2 on 2026-03-23 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
    ]
